// AUTO-GENERATED by scripts/gen-changelog.cjs (pre-commit hook). Do not edit.

export interface ChangelogEntry {
  hash: string;
  /** YYYY-MM-DD */
  date: string;
  subject: string;
  /** Body lines, bullet markers already stripped */
  details: string[];
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    "hash": "dd03ff9",
    "date": "2026-08-03",
    "subject": "feat: AI 调用改走服务端代理，新增模型列表与接口测试",
    "details": [
      "修复浏览器 Service Worker 跨域 fetch 被拒后合成 502",
      "「代理请求失败…Failed to fetch」的问题：AI 请求不再由浏览器",
      "直连供应商，改为经认证的 Next.js Route Handler 转发。",
      "服务端网关：",
      "新增 /api/ai/{models,test,generate,stream}，均要求 GitHub 登录",
      "出站地址策略：生产禁回环/私网/链路本地/云元数据，DNS 解析",
      "后校验，不跟随重定向，超时映射",
      "三协议适配器（OpenAI 兼容/Claude/Gemini）统一 URL 规范化、",
      "鉴权头、响应解析与归一化 SSE；修复 Gemini /v1beta 重复拼接",
      "结构化错误码，上游响应体截断脱敏，不含密钥/堆栈",
      "客户端：",
      "ai-helpers 不再构造供应商 URL/鉴权头，改调同源接口",
      "重试按结构化错误码分类，保留章节断点与草稿语义",
      "AISettingsModal 增加「获取模型」可搜索下拉+手输回退、",
      "「测试模型」真实最小生成测试，配置改动标记结果过期",
      "清理与文案：",
      "删除 public/ai-worker.js，移除 SW 注册，新增注销旧 Worker 组件",
      "修正用户协议/首页/页脚隐私文案（密钥经服务端转发、不落库）",
      "新增 Vitest 测试框架与 .env.example",
      "121 个测试通过，lint 仅剩既有基线问题。"
    ]
  },
  {
    "hash": "fe28dd3",
    "date": "2026-08-01",
    "subject": "feat: improve copyright manual generation and review",
    "details": []
  },
  {
    "hash": "fcc14eb",
    "date": "2026-07-31",
    "subject": "feat: editable review rules, evidence-checked revision, raw line counting",
    "details": [
      "Review rules are now user-editable and importable. Two separate buckets — audit",
      "rules (make the reviewer stricter) and writing rules (constrain the generator) —",
      "kept apart because merging them made the reviewer flag its own instructions.",
      "Both are appended verbatim to the relevant prompts. A rules repository can be",
      "imported: read its Markdown, have the AI distil checkable rules, preview, then",
      "merge or replace. Editor reachable from the dashboard and the audit panel.",
      "Targeted revision no longer trusts the anchor blindly. Concrete tokens the",
      "finding accuses the document of containing (quoted spans, ports, versions,",
      "script names, CamelCase identifiers) are extracted and must actually appear in",
      "the located section; when they don't, the user is asked to confirm rather than",
      "rewriting text that may be correct. Ambiguous anchors report the other matching",
      "headings, a dropdown lets the user pick the section by hand, and the revision",
      "prompt now carries a minimum-change rule plus the evidence list with explicit",
      "permission to return the original unchanged. The UI reports when nothing changed,",
      "which is itself a signal the finding was mislocated.",
      "源程序量 was still undercounting after the previous fix: lines were counted on the",
      "comment-stripped copy while blob sizes on the other side of the ratio are raw",
      "bytes, so bytes-per-line came out inflated and every estimate shrank. Counting",
      "now uses raw line counts throughout, the calibration ratio is measured per",
      "extension (a .java line is far longer than a .py line, so one global ratio is",
      "wrong for every language but the average), GitHub's tree `truncated` flag is",
      "surfaced instead of silently reporting a partial total, and a per-extension",
      "breakdown makes the figure auditable."
    ]
  },
  {
    "hash": "e45932b",
    "date": "2026-07-31",
    "subject": "feat: per-finding AI revision; fix 源程序量 undercount",
    "details": [
      "Replace 清理重复章节 with targeted section revision. Audit findings now carry an",
      "`anchor` — the verbatim heading line of the offending section — so each finding",
      "gets an \"AI 修订该段落\" button: locate that section, send only it plus the problem",
      "and the document's heading outline to the AI, stage the rewrite for review and",
      "hand-editing, then splice it back. Everything outside the section stays",
      "byte-identical, and re-auditing shows the new score.",
      "locateSection matches in three passes (exact heading, numbering/punctuation",
      "normalized, substring) and bounds a section at the next heading of the same or",
      "higher level, so nested ### subsections travel with their parent. Non-exact",
      "matches are flagged in the UI. Applying re-locates by heading rather than reusing",
      "stale offsets, since an earlier revision shifts them.",
      "The dedupe button is gone: it only caught exact heading repeats, so on a document",
      "the audit called \"重复三次\" it reported 未发现重复 and read as broken. Continuation",
      "merging at generation time already prevents new duplication; existing duplication",
      "is better handled as a finding to revise.",
      "源程序量 fix: counting used filterByLanguageRatio, which narrows to the top three",
      "extensions for the code appendix. Every other language was silently dropped, so a",
      "Vue/TS-dominant repo lost its Kotlin, Java and Python files — ~100k lines",
      "reported as ~8k. Counting now uses its own selector over all non-NON_CODE files,",
      "shared with fetchRepoStats and estimateRepoSourceLines so the pre-generation",
      "figure and the registered figure agree. Progress now reports read vs. estimated",
      "file counts."
    ]
  },
  {
    "hash": "c94a5c9",
    "date": "2026-07-30",
    "subject": "fix: cut manual duplication, README-derived description, line recount",
    "details": [
      "Generated manuals scored badly for three reasons, all addressed here:",
      "Chapter continuation turns often re-emitted the chapter from its heading, and",
      "the old code blindly concatenated, so a chapter could appear three times over.",
      "Continuations are now merged: a restarted chapter is detected and either",
      "replaced or section-deduped, echoed tails are trimmed, and a final pass keeps",
      "one copy of each chapter and each section. The model is also told when a",
      "chapter looks complete so it can stop instead of padding.",
      "The manual prompt now forbids inventing languages, ports, version numbers and",
      "script/executable names, which is what produced the KT/5432/install.sh",
      "hallucinations. Each chapter receives the section outline written so far so",
      "module names stay consistent across chapters.",
      "项目描述 is distilled from the README by AI instead of copying GitHub's",
      "one-line slogan; that field feeds metadata generation and every chapter.",
      "AI 核对 is now available inside 编辑项目 and operates on the draft being edited,",
      "with applied suggestions landing in the form rather than behind it.",
      "源程序量 can be re-estimated on demand: samples files across the repo to",
      "calibrate bytes-per-line instead of assuming a fixed 34.",
      "Compliance term replacement extended to divination-flavoured module names",
      "(八字/命理/风水/求签), and both review prompts now steer away from writing such",
      "modules into 主要功能."
    ]
  },
  {
    "hash": "57d6f28",
    "date": "2026-07-30",
    "subject": "feat: version badge with changelog; fix source line count",
    "details": [
      "源程序量 showed ~200 lines because it summed only the files actually downloaded",
      "for the code appendix — fetchRepoFiles caps at 200 files / 500k chars, so any",
      "repo past the cap was reported at the cap instead of its real size.",
      "Count lines from downloaded files and estimate the rest from tree blob sizes,",
      "calibrating bytes-per-line against this repo's own sampled files",
      "Base the pre-generation estimate on code files only; counting lock files,",
      "JSON fixtures and SVGs inflated the number",
      "Stop treating an empty file as one line, and report read failures instead of",
      "silently counting failed fetches as empty files",
      "Version badge:",
      "Show the version in the header of every page, not just the dashboard",
      "Clicking it opens a changelog built from the git log at commit time by",
      "scripts/gen-changelog.cjs (run from the pre-commit hook). Baking it in avoids",
      "the unauthenticated GitHub API rate limit and works offline.",
      "Each entry links to its commit on GitHub",
      "Also point the footer/header GitHub links at the current repo."
    ]
  },
  {
    "hash": "9b15670",
    "date": "2026-07-30",
    "subject": "fix: normalize persisted project metadata on read",
    "details": [
      "\"b.languagesExtra.join is not a function\" crashed the project detail page.",
      "Applying an AI suggestion wrote a string into an array-typed metadata field:",
      "the fallback branch only rejected unknown keys, and languagesExtra is a known",
      "one, so it passed the check and was persisted with the wrong type.",
      "Normalize metadata and project records in getProjects: arrays stay arrays,",
      "strings split back into arrays, text fields join arrays, sourceLines and",
      "status fall back to valid values, records without an id are dropped. This",
      "repairs data already written by an earlier build, so no manual cleanup.",
      "Refuse to apply a suggestion whose target field currently holds an array,",
      "pointing the user at the checkbox editor instead of corrupting the value.",
      "localStorage records have been written by several app versions, so a field's",
      "type was never guaranteed; coercing on read keeps the UI's array calls sound."
    ]
  },
  {
    "hash": "4cf6856",
    "date": "2026-07-30",
    "subject": "fix: cut PDF render memory, guard storage quota, add error boundary",
    "details": [
      "The page went blank (\"This page couldn't load\") right as generation finished —",
      "a renderer OOM, which leaves no catchable JS error.",
      "PDF rendering:",
      "Hand jsPDF binary image data via canvas.toBlob instead of a base64 data URL;",
      "the base64 string held ~2.7x the raw bytes per page and every page was kept",
      "until output()",
      "Release each canvas and yield between pages so the browser can reclaim them",
      "Cap the manual at 60 body pages, keeping the first 30 and last 30 that 一般交存",
      "actually requires, so page count can no longer grow unbounded",
      "Storage:",
      "Route project writes through a helper that reports quota exhaustion as a",
      "readable error instead of throwing from a render path",
      "Keep the rendered PDFs when persisting the manual fails, and let per-chapter",
      "draft saves fail silently rather than aborting a running generation",
      "Resilience:",
      "Add an ErrorBoundary around the project detail page and dashboard so a render",
      "crash shows the cause with retry/back actions",
      "Drop non-null assertions on getProject and guard createObjectURL",
      "Also: AI 核对 now checks feature coverage (reporting detected capabilities and",
      "ones missing from 主要功能) and its suggestions are editable before applying."
    ]
  },
  {
    "hash": "d4f9320",
    "date": "2026-07-30",
    "subject": "feat: keep generation alive across navigation, add review/confirm/version tooling",
    "details": [
      "Generation runtime:",
      "Move generation into a module-level run registry outside React, so SPA",
      "navigation no longer aborts it or falsely marks the project FAILED",
      "Refuse to start a second run for a project that already has one in flight,",
      "which previously let a stray resume click corrupt the shared draft",
      "Re-attach to a live run on remount; collect results even if the run finished",
      "while no page was mounted",
      "AI proxy:",
      "Strip transport-encoding headers when forwarding in the service worker; the",
      "copied content-encoding made the browser double-decompress plain bytes and",
      "surfaced as a bare \"Failed to fetch\" on the audit/review calls",
      "Fall back to direct fetch when no worker controls the page, and wait for the",
      "worker before one-shot JSON calls",
      "Retry review/audit/metadata requests and report actionable errors",
      "Metadata accuracy:",
      "Detect languages from GitHub Linguist byte counts instead of AI guesses and",
      "extension counting",
      "Ground metadata prompts in README, dependency manifests, and module layout",
      "Store repoDescription and backfill it from the API; prompts previously",
      "received the repo URL where a description was expected",
      "Raise the token budget for JSON responses so replies stop being truncated",
      "Also: AI metadata review and manual audit with suggestion apply, full metadata",
      "editing in the project form, confirmation dialogs for destructive/long actions,",
      "and automatic patch version bumping via a pre-commit hook."
    ]
  },
  {
    "hash": "bbbd28f",
    "date": "2026-07-30",
    "subject": "feat: add AI review features for metadata and manual docs",
    "details": [
      "Add AI metadata review: check project info against repo reality",
      "Add AI manual audit: detect hallucinations and assess pass probability",
      "Add force-regenerate checkbox when editing project name/version",
      "Persist reviewContext (fileTree/languages/codeSummary) for post-refresh reviews",
      "Robust JSON extraction from AI responses",
      "UI with warm & earthy design following project style guide"
    ]
  },
  {
    "hash": "29cb0ec",
    "date": "2026-07-29",
    "subject": "Show manual draft resume actions",
    "details": []
  },
  {
    "hash": "27cf46c",
    "date": "2026-07-29",
    "subject": "Support editing project branch",
    "details": []
  },
  {
    "hash": "f518045",
    "date": "2026-07-29",
    "subject": "Specify repo branch and soften copyright wording",
    "details": []
  },
  {
    "hash": "7dfc93f",
    "date": "2026-07-29",
    "subject": "fix: 页面关闭/刷新后不再卡在「准备中」，断点续生自动恢复",
    "details": []
  },
  {
    "hash": "74db3fa",
    "date": "2026-07-28",
    "subject": "fix: improve PDF quality, pagination, TOC, and chapter-wise generation",
    "details": [
      "Render sharper PDFs with height-based page packing, build a de-duplicated TOC, generate manuals chapter-by-chapter with resume, and allow editing Markdown then re-exporting PDF."
    ]
  },
  {
    "hash": "514069a",
    "date": "2026-07-28",
    "subject": "feat: multi AI providers and resumable manual generation",
    "details": [
      "Support configuring multiple AI providers with a single active selection, and resume/retry 文档鉴别材料 drafts so mid-run failures no longer force a full rewrite."
    ]
  },
  {
    "hash": "950a776",
    "date": "2026-07-28",
    "subject": "fix: handle SSE heartbeats when generating manual docs",
    "details": [
      "Parse AI proxy responses as SSE/NDJSON so \": heartbeat\" lines from reverse proxies no longer break JSON parsing during 文档鉴别材料 generation. Also stream long completions and bust the service worker cache."
    ]
  },
  {
    "hash": "806b365",
    "date": "2026-06-28",
    "subject": "Fix lint baseline",
    "details": []
  },
  {
    "hash": "d44e85d",
    "date": "2026-06-24",
    "subject": "Update README.md",
    "details": []
  },
  {
    "hash": "9f1fd32",
    "date": "2026-06-24",
    "subject": "feat: 软著通 - 一键生成中国软件著作权申报材料",
    "details": [
      "GitHub OAuth 登录",
      "多协议 AI 支持（OpenAI/Claude/Gemini），默认 OpenAI",
      "Service Worker 代理 AI 请求避免 CORS",
      "智能代码筛选 + 自动去注释",
      "自动生成软件名称、分类、编程语言、技术特点",
      "程序鉴别材料 PDF（前23+后22页，每页50行）",
      "文档鉴别材料 PDF（封面+目录+正文，33-45页）",
      "浅色/深色模式跟随系统",
      "完整登记表单参考 + 复制功能",
      "用户协议签署"
    ]
  },
  {
    "hash": "99fe30d",
    "date": "2026-06-23",
    "subject": "Initial commit from Create Next App",
    "details": []
  }
];
